AliceLR/megazeux

config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/counter.c
src/game.c
src/window.c
src/world_struct.h

The config parameters standalone_mode and no_titlescreen can now be used
(from MZXRun only) to create standalone versions of MZX with the ability
to fully customise the player's experience. See config.txt for details.

Added standalone mode

---

config.sh
docs/changelog.txt
src/util.c

We may want to implement this in a better fashion, especially for
standalone releases. On Windows there is no problem, but on other
operating systems if each standalone game writes over the same
configuration file we will have some problems, particularly if their
include their own settings. The best approach may be to put this setting
in the global config file- read it first, then decide whether or not to
create a per-user config file.

Added per-user configuration file support

---

src/graphics.c

This stops potential uninitialised memory issues. I also changed the
misleading comment checking for the default resolution width/height.

Blank layers after initialising them

---

docs/changelog.txt
src/graphics.c
src/render_gl2.c
src/render_glsl.c

Ironically, this mainly involved removing existing endian checks.
The screenshot fix was not included in the changelog as the regression is also new to 2.90.

Made opengl2 and glsl endian-correct

---

src/render_sdl.c

This fixes fullscreen support for the opengl-based renderers. No changelog entry as this only fixed a problem with SDL 2 and 2.90 is the first version using SDL 2 as a default.

Removed SDL hw renderer from opengl

---

docs/changelog.txt
src/counter.c
src/graphics.c
src/graphics.h
src/robot.c
src/scrdisp.c

+ [ message boxes now use the same screen mode as everything
else. Same with scrolls. (Lancer-X)
+ spr#_setview now works with unbound sprites. It's pretty nasty
as the viewport can't scroll with pixel precision, but the new
behavior should still be better than the old. (Lancer-X)

Fixed unbound smzx msgbox and setview

---

src/graphics.c

Fixed regression added by 711709cc8e0b7271c594cf10f585750dfb572ace causing SMZX mode to not work in the editor (and possibly causing other problems with changes to SMZX modes).

Fixed smzx editor regression

---

assets/shaders/tilemap.frag
assets/shaders/tilemap.smzx.frag
docs/changelog.txt

Intel HD cards have some peculiar inaccuracies when it comes to GLSL, and this causes problems with MZX's GLSL renderer.

Fixed GLSL on Intel HD cards

---

scripts/msys2-buildscripts/mingw-build.sh
scripts/msys2-buildscripts/mingw-release-single.sh
scripts/msys2-buildscripts/mingw-release.sh

The build script now checks out the remote branch and builds that rather
than relying on local branches which can cause problems. The release
script is now multithreaded and should run much faster.

Updated msys2 build scripts

---

src/audio_sdl.c
src/audio_xmp.c
src/graphics.c
src/platform_dummy.c
src/util.c
src/util.h
src/window.c
src/world.c

- make audio_sdl.c use SDL 2.0's OpenAudioDevice. This enables SDL2's transparent audio conversion in case a given SDL_AudioSpec is not supported.
- fix audio_xmp.c's frequency logic further
- allow new renderers to only implement render_layer and not render_graph
- mark platform_dummy.c's __update_event_status as bool for consistency
- implement join_path_names to join two paths together without duplicated separators

Assorted bugfixes from port work

---

config.sh
docs/changelog.txt
src/editor/block.c
src/editor/block.h
src/editor/board.c
src/editor/board.h
src/editor/edit.c
src/editor/edit.h
src/editor/edit_di.c
src/editor/edit_di.h
src/editor/fill.c
src/editor/fill.h
src/editor/select.c
src/editor/select.h
src/editor/undo.c
src/editor/undo.h
src/util.h

Board/overlay/vlayer undo functionality. Use Ctrl+Z to undo, and Ctrl+Y to redo. Note that quite a few things will clear the entire undo stack (a temporary list is located in the changelog; this should be moved elsewhere).

Editor undo

---

arch/wii/CONFIG.SDLWII
arch/wii/CONFIG.WII
arch/wii/Makefile.in
arch/wii/pad.config.sdl
config.sh
src/Makefile.in
src/configure.c
src/main.c
src/platform_sdl.c

Added SDL support for the Wii since our regular Wii port is currently more unstable than SDL Wii is (Mr_Alert is currently working on this, however). Right now, SDL has to be explicitly disabled using --disable-sdl to build without SDL.  The button mapping for SDL Wii is a bit different from our regular mapping, but the controls themselves should be close to normal.

Added optional SDL support for Wii builds

---

src/utils/Makefile.in

It seems it was left out by mistake.

Delete 'ccv' program on 'make clean'

---

src/editor/Makefile.in

This change was required when I performed a stock build on macOS, otherwise there were undefined references to SDL clipboard functions.

Include SDL when linking on macOS.

---

src/legacy_world.c

The password buffer is declared as a 15 character array. I don't know why the loop to null out unused bytes has always counted up to 16, but it was smashing the stack in my build.

Avoid overflowing the password buffer during decryption.

---

src/main.c
src/network/manifest.c
src/network/manifest.h
src/updater.c

Failed deletions in the updater now trigger error messages and rewrite `delete.txt` so MegaZeux can try to delete them again the next time it starts.  Additionally, files that couldn't be overwritten (e.g. `core.dll`) are renamed to more unique temporary locations to prevent collisions during future updates.

Improved updater deletion failure handling

---

src/counter.c
src/editor/board.c
src/editor/debug.c
src/editor/edit.c
src/expr.c
src/game.c
src/graphics.c
src/legacy_board.c
src/legacy_robot.c
src/legacy_world.c
src/mzm.c
src/old/legacy_save.c
src/robot.c
src/robot.h
src/run_robot.c
src/sprite.c
src/str.c
src/utils/checkres.c
src/utils/downver.c
src/world.c
src/world.h

All (hopefully) raw version magic numbers in version checks across MZX have been replaced with enum values in world.h to make them more readable.  The macros WORLD_VERSION, WORLD_VERSION_PREV, and WORLD_LEGACY_FORMAT_VERSION have been replaced with MZX_VERSION, MZX_VERSION_PREV, and MZX_LEGACY_FORMAT_VERSION, respectively.  Finally, the function counter list has been reformatted to be infinitely more readable.

Refactor version checking

---

arch/mingw/Makefile.in
src/audio/audio_vorbis.c
src/audio/audio_wav.c
src/audio/ext.c
src/audio/sampled_stream.c
src/compat.h
src/compat_sdl.h
src/editor/clipboard_win32.c
src/event.c
src/event.h
src/event_sdl.c
src/graphics.c
src/main.c
src/network/dns.h
src/network/socksyms.c
src/network/socksyms.h
src/platform.h
src/platform_endian.h
src/render_sdl.c
src/thread_sdl.h
src/utils/checkres.c
src/utils/png2smzx.c
src/window.c
src/zip.c

Changes `compat.h`, `platform.h`, and `platform_endian.h` to reduce the number of times `SDL.h` and `windows.h` are needlessly included.  This improves compile times on Windows somewhat.
Also included are misc. fixes for problems encountered during this.

Improve compile times on Windows

---

src/Makefile.in
src/audio/audio_modplug.cpp

I needed to do this in order to get a working libmodplug build. Dunno if this is a refactor-related regression (not sure when the last Modplug build was created) or some other oddity, but here ya go.

Fixed libmodplug compilation.

---

arch/unix/megazeux.desktop
arch/unix/mzxrun.desktop

At some point, freedesktop.org deprecated the Encoding element and the Application category. This PR removes those from our desktop files.

Removed deprecated elements/categories from .desktop files.

---

docs/changelog.txt
src/graphics.c
src/graphics.h
src/render_gl1.c
src/render_gl2.c
src/render_glsl.c
src/render_sdl.h
src/settings.c
src/window.c
src/window.h

Enables switching renderers at runtime and adds an option to the settings menu to do so. This feature is **experimental**.

Enable runtime renderer switching

---

config.sh
docs/changelog.txt
src/render_egl.c
src/render_egl.h
src/render_gl.h
src/render_gl1.c
src/render_gl2.c
src/render_glsl.c
src/render_sdl.c
src/render_sdl.h

The OpenGL ES compatibility hacks in MZX are currently tied to the `CONFIG_EGL` define, which exists for using an EGL platform without SDL (at one point necessary for Android). This is problematic since the OpenGL ES hacks are required for the Switch #166, Emscripten #169, and Android #142 ports, all of which are now based on SDL2 but use OpenGL ES (or compatible) implementations under the hood.
This pull request adds a new config.sh option `--enable-gles` that generalizes the OpenGL ES fixes @asiekierka and I have had to implement for these branches. These platforms can now just force enable this option. This option may also be useful for future ports or Linux on embedded platforms.

Add config option to enable OpenGL ES compatibility hacks

---

config.sh
config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/graphics.c
src/graphics.h
src/render_sdl.c
src/render_sdl.h
src/render_softscale.c
src/render_yuv.c

This adds a config option to make fullscreen mode a borderless window the size of the current desktop, which should be very useful for people who use multiple monitors or who hate fullscreen messing up their other windows. Only works for SDL 2.0 right now.

Add 'fullscreen_windowed' config option

---

config.txt
docs/changelog.txt
docs/keycodes.html
src/configure.c
src/event.c
src/event.h

Allow mapping joystick values and joystick actions to keys by name instead of by value.

Add support for mapping joysticks to key names

---

Makefile
config.sh
docs/changelog.txt

Adds config flags to build with some sanitizers. These add runtime instrumentation code to check for invalid memory use/leaks/race conditions/uninitialized memory use/etc. and currently require Linux, FreeBSD, or Mac OS X to use. MemorySanitizer additionally requires clang.

Add config flags for AddressSanitizer/MemorySanitizer/ThreadSanitizer

---

docs/changelog.txt
src/audio/audio_wav.c
src/editor/edit.c

This removes WAV from the list of extensions to display when selecting a board mod and adds some ~~warnings~~ debug messages when attempting to use SAM or WAV files over a sufficient size (currently 4MiB). This is meant to deter users from using massive WAV files instead of OGG. Some or all of this might not get merged.

Remove WAV from list of mod extensions, add WAV filesize warnings

---

docs/changelog.txt
src/utils/checkres.c
src/zip.c

Adds some long-needed improvements to checkres:
* checkres can now be given a directory as a base file, which it will search for .MZX/.MZB files and report on as a whole.
* checkres now displays the board #, robot # (with line and x/y position on the board), or sfx # of the reference to a particular file.
* checkres now has a flag to display missing files only (`-M`). This is still the default option, but previously it couldn't be selected after selecting one of the other status options before.
* Other new flags: display created files only (`-C`), display found files only (`-F`), display unused files only (`-U`), also display created files (`-c`), also display found files (`-f`), also display missing files (`-m`), also display unused files (`-u`).
* checkres now has flags to control the …

Add checkres wildcard matching and verbose output, sorting, status options

---

config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/game.c

This adds a [config option to start MegaZeux in test mode](https://www.digitalmzx.net/forums/index.php?app=tracker&showissue=769), as if the user pressed Alt+T in the editor. As with normal testing, all debug features are available, but exiting testing will exit MZX. This only works with the "megazeux" executable specifically. A second config option allows the user to specify a particular start board.
Example:
```megazeux caverns.mzx test_mode=1 test_mode_start_board=20```
This tests Caverns of Zeux starting from the Golden Warrior board.

Add config option to start MZX in test mode

---

arch/nds/dlmalloc.c
arch/nds/dlmalloc.h
arch/nds/extmem.c
arch/nds/extmem.h
arch/nds/malloc_opts.h
arch/nds/platform.c
arch/nds/ram.c
src/Makefile.in

* POWER_ALL_2D is used instead of POWER_ALL - this means the unused 3D/geometry cores are not initialized, saving battery
* With regards to extended RAM, dlmalloc has been updated from 2.8.3 to 2.8.6.
* When extended RAM is missing, boards are no longer unnecessarily copied around in memory.
* When extended RAM is present, memory copies should, theoretically, now be slightly (10-20%) faster on real hardware.

nds: touchups

---

arch/emscripten/web/src/index.js
arch/emscripten/web/src/storage.js
arch/emscripten/web/src/storage_emscripten.js

This fixes various issues with the Emscripten port's frontend blocking the release of HTML5 builds.
Would be nice, but probably won't bother with:
* Implement `rename`. For now it just prints a console error instead of crashing MZX. Prevented by FS API nightmare code
* Fix mkdir. This uses `mknod` which intentionally fails for directories currently. The `createNode` function also ignores the incoming mode and errors when creating a directory. It'd be nice to create directories even if they aren't stored, but I'm not sure it's worth the effort and potentially breaking something right now.

Various Emscripten frontend fixes

---

arch/emscripten/web/res/index.html
arch/emscripten/web/src/index.js
arch/emscripten/web/src/storage.js
arch/emscripten/web/src/storage_emscripten.js
docs/changelog.txt

This branch fixes some bugs that have been found in the Emscripten frontend since MZX 2.92b's release.

Fix more Emscripten frontend issues

---

arch/emscripten/web/src/storage.js

Apparently, this mostly means "pre-Chromiumified Edge" in practice, so you might want to skip it - just putting it out there as Zeta has a matching fix.

emscripten: fix IndexedDB support on certain/older browsers

---

src/counter.c

This behaviour (using BYTE >= 14 to write into succeeding characters) is something actually done in production (by Logicow's Summer DoZ 2005 invitation; listed on DigitalMZX as "Day of Zeux Invitation"). To reproduce, compare the .MZX file's intro screen in "software" and "glsl".
Special care is taken to not allow overflowing into the 2.90+ additional charsets. (I wonder what the behaviour was in 2.8x - out-of-bounds read/write?)

fix counter char writes on certain renderers when BYTE >= 14

---

config.txt
src/configure.c
src/configure.h
src/game.c
src/window.c
src/window.h

* Added optional save slot support.
* Added three config.txt options to control this behavior: `save_slots`, `save_slots_name`, and `save_slots_ext`. These values can be overridden in game.cnf.

Save Slots

---

arch/3ds/keyboard.c
arch/nds/event.c
arch/wii/event.c
docs/changelog.txt
src/core.c
src/core.h
src/editor/edit.c
src/editor/robo_ed.c
src/editor/window.c
src/event.c
src/event.h
src/event_sdl.c
src/game.c
src/intake.c
src/intake_num.c
src/window.c

This branch implements an event text buffer and SDL_TEXTINPUT handler. Both intake implementations have been modified to read all input text characters instead of a single char, making typing to them more responsive than before and allowing them to use the normal MZX UI framerate. Additionally, this adds a fallback for SDL implementations that don't generate SDL_TEXTINPUT events (SDL 2+, example: PS Vita?) or return unicode values as part of the key press event (SDL 1.2, example: Pandora).
A side effect of the way SDL_TEXTINPUT is implemented is repeats can't be distinguished from initial presses, so unicode key repeat is currently disabled for SDL 2 builds.
Windows x64 test build: [mzxgit-x64.zip](https://github.com/AliceLR/megazeux/files/4332082/mzxgit-x64.zip)

Properly handle SDL_TEXTINPUT, add event text buffer

---

docs/changelog.txt
src/counter.c
src/counter_struct.h
src/editor/debug.c
src/memfile.h
src/mzm.c
src/str.c
src/world.c

This further reduces some of the bloat the counter/string structs have acquired over time, makes counter/string allocation account for the extra padding bytes in the structs, and fixes the signedness of the counter/string list counts and allocation sizes so MZX (hopefully) won't crash at 1 billion counters anymore. It also adds checks to prevent these from going over 2 billion (though the string check currently triggers a fatal error ☹️).
World for testing counter creation: [new_ctrs_per_second.zip](https://github.com/AliceLR/megazeux/files/4383818/new_ctrs_per_second.zip)

Decrease counter/string allocation sizes, fix signedness in lists

---

config.sh
contrib/khash/khashmzx.h
docs/changelog.txt
src/Makefile.in
src/counter.c
src/counter_struct.h
src/legacy_world.c
src/str.c
src/utils/checkres.c
src/utils/hlp2html.c
src/world.c

Fix khash 2^31 bug, cache hash values in key struct

---

docs/changelog.txt
src/counter_struct.h
src/hashtable.h
src/io/zip.h
src/memcasecmp.h
src/str.c

This branch fixes undefined alignment behavior in memcasecmp that could potentially cause performance issues or crashes on some platforms. Additionally, counter names and string names/values are now aligned to 4 bytes and hash tables use a special case version of memcasecmp roughly equivalent to the older memcasecmp to bypass extra checks.

Fix memcasecmp alignment issues

---

docs/changelog.txt
src/Makefile.in
src/audio/ext.c
src/configure.c
src/editor/char_ed.c
src/editor/edit.c
src/editor/robo_ed.c
src/io/fsafeopen.c
src/io/path.c
src/io/path.h
src/main.c
src/render_glsl.c
src/updater.c
src/util.c
src/util.h
src/utils/Makefile.in
src/utils/checkres.c
src/utils/downver.c
src/utils/hlp2html.c
src/utils/utils_alloc.h
src/window.c
src/world.c

This branch moves a set of functions for manipulating paths out of util.c to `src/io/path.{c,h}` and refactors them to be safer and more consistent. A utils-specific check_alloc header has also been added so fewer utils need to link util.o now (avoiding a dependency chain caused by various util.c functions requiring the path functions).

Refactor path functions out of util.c

---

src/editor/edit.c
src/legacy_robot.c
src/legacy_robot.h
src/mzm.c
src/mzm.h
src/old/legacy_save.c
src/old/legacy_save.h
src/run_robot.c
src/util.c
src/util.h

This branch removes some memory reading functions from util.c that were added before memfile.h and replaces them with the equivalents from memfile.h.

Remove util.h mem_* functions

---

contrib/libxmp/src/loaders/mod_load.c
contrib/patches/libxmp/17-libxmp-4.4.1-reduce-mod-pattern-restrictions.patch
contrib/patches/libxmp/README

* Makes pattern validation slightly more lenient to allow some MODs (like drwho.mod) to play.
* Source: cmatsuoka/libxmp@fa8ede35b76f23ea0d93f8ab22b2162469d49bc0

Pulled in upstream libxmp MOD validation behavior

---

src/editor/block.c
src/error.c
src/utils/ccv.c
src/utils/checkres.c
src/utils/hlp2html.c

This fixes some issues found by new warnings in GCC 10 as well as (an unfortunately small number of) any legitimate issues found by `-fanalyzer`. All of the legitimate issues found by `-fanalyzer` in its current state were MZX using `malloc` or `calloc` instead of the check_alloc functions.

Fix warnings for GCC 10

---

arch/emscripten/web/res/mzxrun_loader.js
arch/emscripten/web/src/index.js
arch/emscripten/web/src/storage.js
arch/emscripten/web/src/storage_emscripten.js
arch/emscripten/web/src/util.js
arch/emscripten/web/src/zip.js

This branch relicenses the Emscripten frontend JavaScript files to the MIT license to match [its upstream counterpart](https://github.com/asiekierka/zeta/tree/master/web) (with the permission of @asiekierka).

Relicense Emscripten frontend to MIT license

---

arch/compat.inc
unit/Makefile.in
unit/io/memfile.cpp

This replaces compiler checks in `arch/compat.inc`  that relied on grep constructs that seem to be broken in or not supported by OpenBSD's grep, including alternation (`|`) and one-or-more (`+`) matching. This also tries to detect situations when CC=`cc` and CXX=`g++` causes a mismatch between compilers and disables specific compiler version checks and prints a warning when this occurs.
As a bonus, this also fixes `-pedantic` in `unit/Makefile.in` and issues with a unit test that for some reason GCC thought was fine.

Fix clang version detection for OpenBSD

---

arch/emscripten/Makefile.in
arch/emscripten/web/res/index.html
src/render_sdl.c

This branch fixes problems caused by Emscripten >=1.39.5 and Emscripten's SDL 2.0.10 fork that weren't actually fixed in 2.92d.

HTML5 port fixes for Emscripten >=1.39.5 and SDL 2.0.10

---

arch/emscripten/web/res/mzxrun_loader.js
src/audio/audio_sdl.c

Safari requires audio events to occur immediately after a user interaction event in order to unlock an audio context. This PR creates and unlocks an audio context during initialization and, if necessary, replaces SDL's audio context with the unlocked one.
This works well on Safari (tested on both macOS and iOS), as well as Chrome (Linux). There is a tiny issue on Firefox where the audio unlock routine can be triggered if the user mashes left-click on the canvas while the page is loading (the DOMContentLoaded event listener largely mitigates this, but it isn't foolproof). It must be emphasized that the user has to really, _really_ be trying to break this, and even then it's not a sure thing.
I tried several workarounds for this, but the check for that delayed audio context state change …

Added Safari support to the Emscripten build.

---

config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/editor/configure.c
src/editor/configure.h
src/editor/edit.c
src/event.c
src/event.h
src/event_sdl.c
src/graphics.c
src/graphics.h
src/main.c
src/render.c
src/render_gl.c
src/render_gl.h
src/render_gl2.c
unit/Makefile.in
unit/Unit.hpp
unit/configure.cpp

This implements the config file validation improvements from #170 without so much of the disgusting macro/offsetof hackery. Unfortunately, this means there's still a lot of boilerplate (but really, I'll take that over what the previous attempt at this ended up like).
Things carried over from the original PR:
New things:
Other tasks:
Things missing from the original PR:
* Editor `include`. I don't like the original idea of having two separate include handlers and changing the way the argv parser handles options. I think a better approach is to register `find_change_option`/config struct pairs at startup and keep one set of functions for loading configuration instead of two. This should be a separate commit.

Improve config file validation for most settings, fix config bugs

---

docs/changelog.txt
src/configure.c
src/configure.h
src/editor/configure.c
src/editor/configure.h
src/editor/edit.c
src/main.c
src/run_stubs.c
src/run_stubs.h
src/world.c
unit/Makefile.in
unit/Unit.hpp
unit/configure.cpp

This branch gets rid of the `set_editor_config_from...` functions and replaces them with a registry (similar to the `audio/ext.c` registry). This allows both config structs to be populated at the same time instead of parsing the config file twice. This also should fix a bug where the `include` directive would not work for editor settings in any version after the editor config was split from the main config (allowing things like putting extended macros in a separate config file).

Use config setting registry instead of separate set_config functions

---

arch/emscripten/web/src/index.js
arch/emscripten/web/src/zip.js
docs/platform_matrix.html

This branch fixes the HTML5 port to work with newer releases of Emscripten, where `Module()` now returns a proper Promise instead of the module object. This mainly just required fixes to the way emzip is initialized and moving the FS initialization from `Module.then()` to `Module["preRun"]`. The `window.MzxrunInitialize` function now returns a Promise (like it did before emzip was added). As a bonus, I added a couple of doc comments.

Fix HTML5 port for Emscripten 1.39.19

---

docs/changelog.txt
src/legacy_world.c

This branch rewrites `decrypt()` to process blocks instead of the entire file in memory, which for SOME REASON seems to cause crashes in the DOS port. Also, if the initial backup filename fails (for example, if the OS expects a 8.3 name), it will try a shorter backup filename.

Rewrite decrypt() to use less memory

---

docs/changelog.txt
src/render_gl.h
src/render_gl2.c
src/render_glsl.c

All textures in the OpenGL renderers are currently read from buffers using the `GL_UNSIGNED_BYTE` pixel format mode for compatibility with GLES and all instances of pixel packing in these renderers (the palette for the background colors in the opengl2 renderer; the palette, indices, and layer data in the glsl renderer) assumed an ordering equivalent to `GL_UNSIGNED_INT_8_8_8_8_REV`. This branch simply adds a function that flips these bytes for big endian platforms.
The layer data bug has existed in the GLSL renderer since 2.83; the palette bugs were introduced in 2.90.

Fix glsl and opengl2 renderers for big endian machines

---

config.txt
src/configure.c
src/configure.h
src/editor/window.c
src/error.c
src/game_menu.c
src/graphics.c
src/graphics.h
src/helpsys.c
src/robot.c
src/scrdisp.c
src/settings.c
src/window.c
unit/configure.cpp

This branch makes all active dialog elements and a few other UIs (char selection, color selection, list menu, main/game menus) use the `cursor_hint` function to place the text cursor next to the highlighted element's current selection or label. This functionality was requested for a screen reader but may be useful to others.

Make active UI elements use cursor_hint

---

arch/psp/Makefile.in
arch/wii/Makefile.in
arch/wii/network.cpp
config.sh
docs/changelog.txt
src/Makefile.in
src/network/DNS.cpp
src/network/Host.cpp
src/network/Socket.cpp
src/network/Socket.hpp

This allows these features to be disabled for platforms that don't support them, whether they're old platforms (e.g. AmigaOS 4) or their console SDKs don't support them (PSP, Wii, Wii U #246). I also added patches to get PSP and Wii to build with network support since I'm tired of manually patching them in for testing (network support shouldn't actually work on either right now, though...). If a platform that doesn't support these tries to build with them enabled it should trigger a compile time error, but this needs more testing.

Add config.sh flags `--disable-getaddrinfo` and `--disable-ipv6`

---

arch/wii/network.cpp
config.sh
src/network/Host.cpp
src/network/Host.hpp
src/network/Socket.cpp
src/network/Socket.hpp
src/updater.cpp

This branch gets network support for the Nintendo Wii port fully working via adding some new `extern "C"` `platform_*` functions to Socket.hpp, which should also make it possible to get networking going on the [Nintendo Switch](https://switchbrew.github.io/libnx/socket_8h_source.html) and the [Nintendo](https://github.com/devkitPro/libctru/blob/master/libctru/include/3ds/services/soc.h) [3DS](https://github.com/devkitPro/3ds-examples/blob/master/network/sockets/source/sockets.c) with (hopefully) little issue. There's also an implementation of `Socket::poll` for the Wii, manual setting of `errno` for the Wii (since the Wii network functions do not set `errno`), and some bugfixes for misc. socket functions that have sketchy/broken/nonexistent Wii implementations.

Implement Wii network support.

---

arch/wii/network.cpp
config.sh
docs/changelog.txt
src/network/Host.cpp
src/network/Socket.cpp
src/network/Socket.hpp

This branch gets network support working for the 3DS and Switch ports and makes some changes to how platform network initialization occurs (gets rid of duplicate `init_ref_counts`, the init implementation used relying on `getaddrinfo`...). For now their platform-specific hooks have just been appended to `Socket.cpp`.

Implement 3DS and Switch network support.

---

src/event.c
src/event.h
unit/configure.cpp

Fixes a regression caused by [e42259b4](https://github.com/AliceLR/megazeux/commit/e42259b4d189de02e12220fabc7053f34b4f9b9a#diff-f4b1dfbfae738858a42e05ae54450e00) where joystick config ranges (example: `joy[1,16].a = key_space`) stopped working for the NDS and 3DS ports. This is a problem as game configs should be using ranges like these for portability.
The bounding check for the joystick mapping functions is now entirely based on the first joystick index (the last index is just clamped to the range of valid joysticks). This means any joystick range starting from 1 should be guaranteed to work on everything. A unit test for the joystick configuration options has also been added to `unit/configure.cpp`.

Add joystick config unit test, fix joystick ranges for NDS/3DS

---

arch/nds/audio.c
docs/changelog.txt
src/audio/audio.c
src/audio/audio.h
src/audio/audio_pcs.c
src/audio/audio_pcs.h
src/audio/sfx.c
src/audio/sfx.h
src/thread_debug.h

Fixes a couple of fairly significant regressions in MZX's audio threading and PC speaker behavior introduced in the transition to SDL:
- The circular buffer used by sfx.c was fine in DOS but is prone to concurrency issues in parallel environments. This is made worse by the fact that either thread was capable of cancelling the entire queue, which made it vulnerable to (very rare) desynchronization issues. A mutex has been added to fix this. ThreadSanitizer still reports some "data races" but these are reads that don't directly affect the state of the queue, so I don't see any point in wrapping them with the lock [(issue)](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=494&st=0#entry4518).
- The annoying audio mutex locking debug messages that were introduced in 2.81f …

Fix audio.c, sfx.c threading issues and PC speaker note cancelling

---

arch/nds/event.c
arch/nds/event.h
arch/nds/render.c

This makes NDS's focus logic work (more or less) the same as 3DS's.
I've noticed a minor issue with how, when the player is in center (Caverns starting board), moving out of focus by touch will only auto-restore focus once the player's on-screen (as opposed to on-board) position changed, but I suspect it may be too complicated to fix for 2.92f. You may also deem this not to be an issue, but it feels off to me.

nds: unify focus logic with 3DS, fixing bugs

---

docs/STYLE.md
src/compat.h
src/render.c
src/render.h
src/render_layer.cpp
src/render_layer.h
src/render_layer_code.hpp
src/render_softscale.c
src/render_yuv.c

MSVC uses `restrict` as part of an attribute so defining `restrict` in compat.h isn't really a great idea. This patch replaces it with `RESTRICT`, documents this in STYLE.md,  and also adds it to more render_layer functions it should have originally been added to.

Fix `restrict` define for MSVC 

---

arch/msvc/Core.vcxproj
arch/msvc/Core.vcxproj.filters

Accommodates the change from `fnmatch.c` to `xfnmatch.c`. There were also some references to nonexistent `libxmp` headers in the VC project that I'd forgotten to clear out. Header references don't affect the build process, but they're useful when editing the code.

MSVC project update: fnmatch.c -> xfnmatch.c

---

contrib/libxmp/Makefile.megazeux
contrib/libxmp/docs/Changelog
contrib/libxmp/include/xmp.h
contrib/libxmp/src/common.h
contrib/libxmp/src/control.c
contrib/libxmp/src/format.c
contrib/libxmp/src/format.h
contrib/libxmp/src/hmn_extras.c
contrib/libxmp/src/load.c
contrib/libxmp/src/loaders/669_load.c
contrib/libxmp/src/loaders/far_load.c
contrib/libxmp/src/loaders/gdm_load.c
contrib/libxmp/src/loaders/it_load.c
contrib/libxmp/src/loaders/med3_load.c
contrib/libxmp/src/loaders/med4_load.c
contrib/libxmp/src/loaders/mmd1_load.c
contrib/libxmp/src/loaders/mtm_load.c
contrib/libxmp/src/loaders/okt_load.c
contrib/libxmp/src/loaders/s3m_load.c
contrib/libxmp/src/loaders/ult_load.c
contrib/libxmp/src/med_extras.c
contrib/libxmp/src/player.c
contrib/libxmp/src/read_event.c

Updates libxmp for the following patches:
* `LIBXMP_NO_PROWIZARD`, which reduces the patch surface area for this fork down to +18 -88, mostly in format.c.
* A fix for Emscripten builds that doesn't affect MZX since libxmp is built directly into MZX. MZX builds still work after adding these changes.
* A fix for the volume/panning/slide update order that affected most formats.
* Crash fixes for various loaders and other misc. fixes.

Update libxmp for LIBXMP_NO_PROWIZARD, misc. fixes.

---

src/io/memfile.h
src/io/vfile.c
src/io/vfile.h
unit/Makefile.in
unit/Unit.hpp
unit/io/memfile.cpp
unit/io/vfile.cpp

Fixes numerous issues with vfile.c and missing functions:
* Added `vfopen_unsafe_ext` and flags to allow specifying a buffer for applicable `vfile`s.
* Append mode now works for memory  `vfile`s.
* Added missing vfile.c functions `vungetc` and `vfputs`.
* Added a FILE implementation for `vfsafegets`.
* `vfseek` past the end of a memory `vfile` now works correctly.
* `vfile_ensure_space` no longer attempts to expand fixed-size memory `vfile`s.
* `memfile` now has a flag to allow seeking past the end of its memory block, which was required to fix memory vfile seeking compatibility with FILE seeking.
* All vfile.h functions (aside from misc. functions for zip.c) are now `UTILS_LIBSPEC`.
* Added vfile.c unit tests.
TODO:

Implement vfile.c missing features/fixes and add unit tests.

---

docs/changelog.txt
src/editor/char_ed.c
src/editor/debug.c
src/editor/edit.c
src/editor/pal_ed.c
src/editor/robo_ed.c
src/editor/window.c
src/editor/window.h
src/game.c
src/io/path.c
src/io/path.h
src/window.c
src/window.h
unit/io/path.cpp

Cleans up some ambiguous parameters to the `file_manager` family of functions and also fixes some minor bugs related to directory selection:
* `allow_dirs` (previously `dirs_okay`) now uses enum values explicitly named `NO_DIRS`, `ALLOW_ALL_DIRS`, and `ALLOW_SUBDIRS`.
* `allow_new` now uses enum values explicitly named `NO_NEW_FILES`, `ALLOW_NEW_FILES`, and `ALLOW_WILDCARD_FILES` (only used by char editor aggregate importing).
* Fixed a bug where `..` would appear in the root for the 3DS and Switch ports (introduced in 2.91X).
* Fixed a bug where `base_dir_name` and `current_dir_name` could sometimes contain different slashes, preventing module/board charset/board palette selection. This issue currently is only known to affect the DJGPP port and was probably introduced in 2.84X (not …

Replace file manager dirs/allow_new flags with enums, fix bugs.

---

src/io/vfile.c
src/io/vfile.h
src/io/vfile_posix.h
src/io/vfile_win32.h
unit/io/vfile.cpp

Adds a function to create real and/or memory vfiles. Also changes vfile expansion to occur in powers of two instead of incrementally.

Add vtempfile and improve memory vfile expansion.

---

docs/changelog.txt
src/editor/robo_ed.c

Fixes the following bugs:
* When no block is marked, pressing Alt+B on a line is supposed to update the line before copying it to the buffer. This bug was introduced by the 2.80X robot editor rewrite.
* Any operation that can send a line containing a extended macro to `add_line` (pasting the clipboard; importing Robotic from a text file; nested macros) caused a crash due to faulty behavior when `add_line` received an error state from `update_current_line` (indicating the added line should be discarded). This regression occurred some time between 2.82 and 2.82b.
* Some bad code/workarounds for the above issue caused an extra line to be emitted when evaluating an extended macro with `split_current_line`. This behavior was also introduced in 2.82b.
Cleanup:
* The debytecode update/package …

Robot editor fixes and cleanup.

---

arch/xcode/MegaZeux.xcodeproj/project.pbxproj
src/editor/Makefile.in
src/editor/clipboard_cocoa.m

This adds a Cocoa clipboard handler to directly access the clipboard instead of relying on the Carbon (discontinued) or SDL2 (expects a UTF-8 encoded input) handlers. Note this hasn't really been tested on older Macs yet so I'm not sure if replacing the Carbon handler entirely with it is a good idea.
Mac OS Roman encoding is used for the clipboard data because it seems to be the only easily supported text encoding that can have all 256 codepoints cleanly converted to/from UTF-8. ISO Latin-1 and Windows 1292, for example, have issues with various codepoints in the 128-159 range.
Fixes [this issue](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=816).

Add Cocoa clipboard handler to replace Carbon/SDL2 handlers for Mac OS.

---

arch/xcode/MegaZeux.xcodeproj/project.pbxproj

Fixes the following issues with the Xcode project (most are my fault or due to things I added ;-():
* ansi.{c,h} were missing from the editor target.
* AppKit.framework was missing from the editor target (required to correctly link clipboard_cocoa.m).
* `USE_HEADERMAP` was causing system headers to pull in MZX headers in place of some system headers, causing numerous compilation issues in clipboard_cocoa.m related to `bool` (which compat.h undefines).
* Added libxmp/src and libxmp/src/loaders to the user header include paths for the core target to fix libxmp compilation after the above change.
* Disabled C++ exceptions and RTTI for all targets.
TODO:

Fix Xcode ansi.c/h, AppKit.framework, and USE_HEADERMAP issues.

---

docs/changelog.txt
src/editor/robo_ed.c
src/graphics.h
src/intake.c
src/intake.h
unit/Makefile.in
unit/intake.cpp

This branch adds a layer of indirection to intake2's text editing event processing and provides functions to override (or manually invoke) the default event handling. This is necessary to fix undo/redo bugs in the robot editor, and also to allow custom implementations of the events for e.g. non-continuous text buffers. It also made it easier to add a unit test for the default fixed buffer operations, so I did.
The draw and click handlers have also been removed from intake2, meaning it no longer needs to be provided a continuous buffer pointer at all. This also opens up the robot editor to future improvements to how it draws the current editing line.

Add intake2 events, unit test, remove intake2 draw/click handlers.

---

docs/changelog.txt
src/editor/robo_ed.c
src/editor/robo_ed.h
src/editor/undo.c
src/editor/undo.h
src/intake.c
unit/intake.cpp

Adds undo (Ctrl+Z) and redo (Ctrl+Y) functionality to the robot editor, the place that probably needed this the most of anywhere in MZX. No guarantees about it not being horribly broken right now, but since it uses internal robot editor list functions to manipulate the list it probably should at least be crash-proof (now that I've fixed the crashes in those functions anyway).
Test build: [mzxgit-x64.zip](https://github.com/AliceLR/megazeux/files/6289163/mzxgit-x64.zip)

Implement robot editor undo/redo.

---

docs/changelog.txt
src/audio/audio_openmpt.c
src/core.c
src/error.c
src/legacy_rasm.c
src/main.c
src/network/HTTPHost.cpp
src/network/Host.cpp
src/nostdc++.cpp
src/render_glsl.c
src/render_layer_code.hpp
src/str.c
src/util.c
src/util.h
src/utils/checkres.c
src/utils/utils_alloc.h
src/world.c

Probably (but maybe doesn't) fixes stdio redirect bugs for the NDS and potentially other consoles with sketchy SDKs by using different file handles for redirected `stdout` and `stderr` (instead of modifying `stdout` and `stderr` directly with `freopen`). This also means vio.c doesn't need to support `freopen` in the future.

Add mzxout and mzxerr, use instead of freopen for stdio redirect.

---

src/io/zip.c
src/io/zip.h
src/io/zip_deflate.h
src/io/zip_deflate64.h
src/io/zip_implode.h
src/io/zip_reduce.h
src/io/zip_shrink.h
src/io/zip_stream.c
src/io/zip_stream.h
unit/io/zip.cpp

Instead of destroying and reallocating `zstream`s repeatedly when reading and writing ZIP files (particularly worlds/saves), the same `zstream` is now reused for every file in the archive. This should ~~moderately~~ slightly? improve saving and loading speeds for embedded platforms where this is a concern. This also gets rid of a pretty disgusting hack in the `zip_archive` struct.

Reuse zstreams between files when reading/writing ZIP archives.

---

config.txt
docs/changelog.txt
src/Makefile.in
src/configure.c
src/graphics.c
src/render_glsl.c
src/renderers.h

Adds a GLSL renderer variant that uses software rendering internally instead of hardware rendering and makes it the new default renderer. This variant is better suited to lower end machines and embedded platforms.
`glsl` performs better than `glslscale` for:
* desktop dedicated video.
* laptop dedicated video.
* Mobile integrated graphics on very simple screens (no or few layers).
`glslscale` performs better than `glsl` for:
* Mobile integrated graphics with more complex screens. `glsl` is extremely slow here but software-based renderers like `glslscale` run great. sai.frag noticeably slower.
* Mac Mini AMD integrated graphics.
* iMac (Core Duo, Snow Leopard) ATI Radeon X1600 gets `glslscale` performance comparable to `softscale` even using sai.frag.
* Laptop Intel HD video in cases where …

Add GLSL scaled software renderer 'glslscale'.

---

arch/3ds/render.cpp
arch/nds/render.c
arch/wii/render_gx.c
arch/wii/render_xfb.c
config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/graphics.c
src/graphics.h
src/old/render_sdl2accel.c
src/render_egl.c
src/render_egl.h
src/render_gl1.c
src/render_gl2.c
src/render_glsl.c
src/render_gp2x.c
src/render_sdl.c
src/render_sdl.h
src/render_soft.c
src/render_softscale.c
src/render_yuv.c
unit/configure.cpp

The `force_bpp` config setting doesn't really reflect the reality of the SDL 2 version of MZX's software renderer, which is that SDL picks a native window format internally and this can't really be changed. This branch adds an "auto" setting for `force_bpp` which makes MZX select the BPP value that SDL picked instead of the other way around. This should fix issues involving blitting being selected by default on platforms where the native pixel format is not RGB888 (encountered in m68k Linux via QEMU with a 16-bit display).
SDL 1.2 can also support the "auto" setting by using the `SDL_VideoModeOK` return value instead of ignoring it.
The nature of the way this is implemented means a renderer `init_video`, `check_video_mode`, or `set_video_mode` function should now always initialize …

Add a force_bpp setting for automatic BPP selection.

---

contrib/libmodplug/src/Makefile.in
contrib/libmodplug/src/libmodplug/sndfile.h
contrib/libmodplug/src/load_gdm.cpp
contrib/libmodplug/src/sndfile.cpp
contrib/patches/libmodplug/14-libmodplug-0.8.9.0-add-gdm-loader.diff
contrib/patches/libmodplug/readme.txt
src/Makefile.in
src/audio/audio_modplug.cpp

This patch replaces gdm2s3m with a real libmodplug GDM loader. This should do effectively the same job as gdm2s3m, except without the intermediate file IO step, directory pollution, and filename translation bugs. (Additionally, it can actually be contributed upstream, so theoretically other projects could benefit from it.)

Add experimental libmodplug GDM loader to replace gdm2s3m.

---

.github/workflows/main.yml
config.sh

Since setting up MSYS2 takes up about half of the time of each MSYS2 workflow, it seems like combining them might be worthwhile to speed things up.

Combine MINGW32/MINGW64 workflows into a single MSYS2 workflow.

---

src/intake.c
unit/Unit.hpp
unit/configure.cpp
unit/intake.cpp

The `INTK_BACKSPACE_WORDS` event default implementation failed to actually move the cursor back to the start of the erased token, causing Ctrl+Backspace in the robot editor to be buggy.
Additionally, cleans up some of the duplicate `ASSERTx` macros in Unit.hpp by making the regular versions allow a variadic message format to pass to `vsnprintf`. The `ASSERTXx` macros in most places still haven't been replaced yet. Since there wasn't a non-message version of `ASSERTXNCMP`, I just replaced that one entirely.

Fix intake INTK_BACKSPACE_WORDS cursor behavior.

---

.github/workflows/main.yml

* The time savings from combining the MSYS2 workflows wasn't worth the longer test duration.
* The container pull times for the dkp workflows are fairly negligible, and doing two PowerPC builds in the same test run is SLOW.

Split MSYS2 and dkp workflows.

---

unit/Makefile.in
unit/Unit.hpp
unit/configure.cpp
unit/editor/stringsearch.cpp
unit/expr.cpp
unit/intake.cpp
unit/io/bitstream.cpp
unit/io/memfile.cpp
unit/io/path.cpp
unit/io/vio.cpp
unit/io/zip.cpp
unit/memcasecmp.cpp
unit/network/Manifest.cpp
unit/network/sha256.cpp
unit/utils/image_file.cpp

Removes the `ASSERTX` series of macros in favor of the new variadic parameters to `ASSERT`. Also fixes a bunch of -pedantic warnings in old GCC versions and clang caused by the variadic macros, switches a lot of standard for loops to range-based for loops, and gets rid of some `snprintf` usage made unnecessary by the updated `ASSERT` macros.

Unit test cleanup, remove ASSERTX macros, fix warnings.

---

.github/workflows/main.yml
Makefile
contrib/libmodplug/src/Makefile.in
contrib/libxmp/Makefile.megazeux
contrib/rad/validate20.cpp
src/Makefile.in
src/network/Socket.cpp
src/nostdc++.cpp
src/pngops.c
src/pngops.h
src/updater.cpp
src/utils/ccv.c
src/utils/png2smzx.c
unit/Makefile.in
unit/Unit.hpp
unit/intake.cpp
unit/io/vio.cpp
unit/network/Manifest.cpp

Moves the usage of `-Wpointer-arith` and `-Wwrite-strings` to the global `CFLAGS` and adds `-Wmissing-declarations` to the global `CFLAGS`. Includes warning fixes for these changes, and also fixes ccv.c's style and the -Wvla warning in ccv.c.

Move misc. warnings from core_flags to global CFLAGS/CXXFLAGS.

---

Makefile
arch/compat.inc
arch/nds/extmem.c
arch/nds/platform.c
src/Makefile.in
src/io/vio.h
src/utils/ccv.c
unit/Makefile.in

Moves some more of the questionable warning handling in `src/Makefile.in` to the main `Makefile`, groups warning flags together, replaces `-W` with `-Wextra`, and gets rid of some obsolete duplicate warning flags in `unit/Makfile.in`.

More compiler warning flags cleanup.

---

docs/fileform.html
src/board.c
src/robot.c
src/utils/downver.c
src/world.c

Cleans up some issues of varying degree in the ZIP world format:
* World names were saved as a null-terminated array instead of as non-terminated string. (Loading of non-array cases was fixed in 2.92d.)
* World name junk data beyond the terminator could still be saved in some cases.
* World module name, input filename, output filename fields were saved with an unecessary terminator.
* Board name loading used sketchy termination that, when combined with boards names that are too short, could leave uninitialized data at the end of the name before the terminator.
* Board names were saved as a null-terminated array instead of as a non-terminated string. Terminator is currently saved for 2.92X compatibility (see above), but this will be removed.
* Robot names, sensor names, and sensor message …

Clean up misc. world/board/object string fields in saves.

---

src/io/vfile.h
src/io/vio.h
src/io/zip.h
src/io/zip_deflate.h
src/io/zip_deflate64.h
src/legacy_robot.c
src/legacy_robot.h
unit/io/zip.cpp

The `memfile` header defines a bunch of inline functions that need to be parsed every time it's included, so I've removed includes of it in other headers.

Remove memfile.h includes from more headers.

---

src/compat.h
src/counter.c
src/helpsys.c
src/io/fsafeopen.c
src/io/fsafeopen.h
src/io/memfile.h
src/io/vio.c
src/io/vio.h
src/io/zip.c
src/io/zip.h
src/legacy_rasm.c
src/network/HTTPHost.cpp
src/rasm.c
src/robot.c
src/str.c
src/util.c
src/util.h
src/world.c
src/world_struct.h
unit/io/memfile.cpp
unit/io/vio.cpp
unit/io/zip.cpp

This cleans up the remaining few features that were using stdio directly rather than vio.c, mostly related to gameplay features in counter.c and str.c. This required fixing `vfilelength` for write mode and making memory ZIPs use vio.c expansion instead of their old direct expansion.

Use vio.c wrapper functions for input/output files, help system, et al.

---

testworlds/run.sh

Fixes an issue creating `megazeux-config` when trying to run `make test` from a MegaZeux repository that exists in a QEMU vfat filesystem. The main use case for this is building MegaZeux in VMs with old Linux distributions that have non-functional Git and/or TLS.

Test worlds: replace ln -s with cp to support QEMU vfat drives.

---

Makefile
config.sh
src/Makefile.in
src/main.c
src/network/Scoped.hpp
unit/Makefile.in
unit/Unit.cpp
unit/Unit.hpp
unit/align.cpp
unit/configure.cpp
unit/editor/stringsearch.cpp
unit/intake.cpp
unit/io/memfile.cpp
unit/io/vio.cpp
unit/io/zip.cpp
unit/memcasecmp.cpp
unit/network/Manifest.cpp
unit/network/sha256.cpp
unit/world.cpp

Removing `#include <string>` and some other misc. includes from Unit.hpp and moving most function definitions to a new compilation unit (Unit.cpp) seems to have further improved the compilation time of the unit tests locally. Opening a PR to see if this helps anything else.
(Separating unit test build from linking only benefits parallel make and is slightly slower in MSYS2 so I didn't bother.)
edit: this *halved* unit test compilation time in my SPARC64 VM.

Remove C++ STL includes and most function definitions from Unit.hpp.

---

Makefile
config.sh

Fixes the following issues:
* Debian deprecated `which`. All usages I found in MZX can be replaced with `command -v`.
* ShellCheck emitted numerous warnings about the usage of `-o` and `-a` in `test`. https://www.shellcheck.net/wiki/SC2166
* ShellCheck emitted warnings about parameter and variable substitution not being quoted to prevent spaces from breaking. https://www.shellcheck.net/wiki/SC2046
* ShellCheck emitted warnings about usage of \`\`  instead of `$(...)` for subshell substitution. https://github.com/koalaman/shellcheck/wiki/SC2006
* ShellCheck emitted a warning about the usage of the invalid `test` operator `==` in one place. https://www.shellcheck.net/wiki/SC3014

Replace 'which' with 'command -v', fix ShellCheck warnings.

---

unit/Unit.hpp
unit/io/vio.cpp

The `FAIL()` macro's invocation of `Unit::exception()` could be mistaken for the wrong constructor. A spot in vio.cpp was also using the wrong variable in an instance of this macro.

Fix Unit.hpp FAIL macro.

---

arch/unix/Makefile.in
src/io/vio_posix.h

This fixes situations where `readdir` fails with `EOVERFLOW` in 32-bit executables running on 64-bit QEMU hosts and/or large filesystems.

Prefer dirent64 over dirent when available on Unix systems.

---

Makefile
testworlds/run.sh
unit/Makefile.in

* Fixed the `run.sh` hang detection loop for implementations of `ps` that don't contain the `-p` option e.g. BusyBox (Alpine Linux).
* Fixed printed errors when `tput` is missing (Alpine Linux).
* The `-q` option for `run.sh` is now shifted off of the arguments list prior to other argument checks. It also now applies to all printed text emitted by `run.sh` instead of just the results.
* Fixed most ShellCheck pedantry for `run.sh`.
* Fixed Makefile warnings caused by some versions of GNU Make trying to optimize `$(shell command -v git)`, causing it to fail.
* The Makefile unit tests now have both `unit` and `unittest` as targets.
* The test worlds now have a `testworlds` target that allows them to execute without first running the unit tests.

Misc. regression test script fixes.

---

unit/Unit.cpp
unit/Unit.hpp
unit/intake.cpp
unit/io/memfile.cpp

* Due to some issues in how the variadic `Unit::exception` constructors were implemented, the wrong constructor could be selected when comparing strings, resulting in a nonsense error report. This has been fixed by replacing the `const char *` argument fields with a new class `Unit::arg` (that does more or less the same thing `std::string` was used for before). Usage of `Unit::arg` also means the `Unit::exception` constructors no longer need to be templates.
* `memcmp` array exception arguments are now handled by `Unit::arg`, meaning several `Unit::exception` constructors are no longer needed and have been removed.
* The `Unit::exception` variadic constructors now use `__attribute__((format(printf)))`. This caught several broken format strings.
* `main` runs `Unit::self_check` before …

Add unit tests self check and misc. unit tests fixes.

---

config.sh
src/Makefile.in
src/io/path.c
src/io/path.h
src/io/vfs.c
src/io/vfs.h
src/io/vio.c
src/io/vio.h
unit/Makefile.in
unit/Unit.cpp
unit/io/memfile.cpp
unit/io/path.cpp
unit/io/vfs.cpp
unit/io/vio.cpp
unit/io/zip.cpp

Adds a virtual filesystem data structure for MegaZeux. Currently it does nothing except pass its own unit tests (as far as I've tested). vio.c integration, file caching, etc. will probably be added in separate patches.
Also cleans up/modifies the IO unit tests so they can build with `--disable-modular` builds and reduces the number of `arraysize` uses in the unit tests.

Add virtual filesystem and misc. unit test tweaks.

---

.github/workflows/main.yml
Makefile
config.sh
src/error.c
src/graphics.c
src/graphics.h
src/render_sdl.c
src/render_soft.c
src/run_robot.c
unit/Makefile.in

MemorySanitizer requires all dependencies to be instrumented to be of much use, which makes it particularly annoying out of the sanitizers to test for projects with dependencies (like MegaZeux).
* The software renderer was closely tied to SDL before, but will now build even with `--disable-sdl`. In this form it is headless and mainly only good for testing, but this change to the software renderer was pretty much going to happen anyway eventually for other reasons. The alternatives here: either get a working instrumented build of SDL (which I initially attempted but it seems messy), or add a separate dummy renderer (cleaner but more readily gives access to a headless renderer which might be frustrating/confusing to users).
* Non-modular builds couldn't build the tests in some cases due to …

Add a MemorySanitizer action + required improvements/fixes.

---

docs/changelog.txt
src/editor/char_ed.c
src/editor/debug.c
src/editor/pal_ed.c
src/editor/robo_ed.c
src/graphics.c
src/graphics.h
src/intake.c
src/robot.c
src/scrdisp.c

Cleans up the five (5!) string drawing loops in graphics.c and replaces them with one. `write_string` and `write_string_ext` now take a flags field instead of `boolean tab_allowed`. This allows a) the mask and line variants of these functions to be removed and b) scrolls to be able to display color codes with less if/else spaghetti and without adding more functions to graphics.c.
The scroll color displaying functionality is limited to 1.x and >=2.93 worlds. Since neither are actually supported right now outside of unmerged branches, this means it doesn't do anything, but it can be verified by modifying the version check!

Overhaul graphics.c string functions and allow colors in scrolls.

---

docs/changelog.txt
docs/keycodes.html
src/event_sdl.c

The `IKEY_UNICODE` handling for SDL 1.2 builds (which combine text/unicode events into key events) was incorrectly handled for SDL 2.0 (which uses separate events), causing it to generate key presses with `IKEY_UNICODE` for unsupported keys instead of just ignoring them.
Also fixes PrintScreen/SysRq and Menu/"Right Click", which were the normal US layout keys that still produced this behavior. SDL 2.0 added new keycode enum values for these but didn't get rid of the old ones, hence them getting overlooked before.

Disable SDL 1.2 IKEY_UNICODE handling for SDL 2.0, fix keys.

---

docs/changelog.txt
src/core.c

Due to the entrance/board edge `vquick_fadein` and entrance `vquick_fadeout` incorrectly being included in the gameplay framerate calculation, some frames could be severely truncated. For board edges this occurs on the second cycle of the board and is noticeable as the player appearing to jump over X=2 or Y=2, among other things. This was introduced as part of splitting up `update` way back in 2.91g.
sdfjksdlkfjsdlkfjdslkfjsdljkld

Fix serious framerate bug related to board edges/entrances.

---

arch/install.inc
arch/unix/Makefile.in
arch/unix/megazeux.desktop
arch/unix/mzxrun.desktop
config.sh

Turns out you can't just dump an icon in /usr/share/icons! This is needed for flatpak specifically but is a good idea to fix in general.

Update unix .desktop files and install the icon to the correct place.

---

docs/changelog.txt
src/robot.c
src/scrdisp.c

* `\n` no longer emits a line break in robot message box color printing lines (introduced in 2.81X). It now prints as char 10.
* Bad termination for the centered color string `&` command combined with the X position calculation no longer causes `color_string_ext` to crash (introduced in 2.84, but hard to reproduce prior to 2.90 for some reason).
* Fixed termination for the option `?` commands that didn't take color codes into account (has existed in some form forever).

Fix message box newline, color string length calculation bugs.

---

arch/3ds/thread.h
arch/dreamcast/thread.h
arch/wii/thread.h
src/network/DNS.cpp
src/platform.h
src/thread_dummy.h
src/thread_sdl.h
src/thread_win32.h
unit/Makefile.in
unit/thread.cpp
unit/thread.hpp
unit/thread_win32.cpp

* Added semaphores to all thread.h implementations that support them.
* Added boolean return values to the following functions: platform_mutex_init, platform_mutex_destroy, platform_cond_init, platform_cond_destroy, platform_thread_create, platform_thread_join.
* Minor style/function order tidying.
* Added a Win32-based thread.h implementation for utilities on Windows, which do not link SDL. This should be used for utilities only as it does not support condition variables and its semaphores are slow.
* Added a set of unit tests for thread.h which are probably very bad!

Implement semaphores and standardize synchronization return values.

---

docs/changelog.txt
src/Makefile.in
src/counter.c
src/platform.h
src/platform_sdl.c
src/platform_time.c
src/robot.c
src/run_robot.c
src/world_struct.h
unit/thread.hpp

* The system time is now stored for the duration of the current Robotic command the first time it is requested. This makes usage of multiple date/time counters in the same command atomic, fixing rare bugs when combining multiple counters.
* System time sampling has been moved to platform_time.c.
* If available at runtime, all Windows builds now use `GetSystemTimePreciseAsFileTime` to get the system time. If not, they directly poll `GetSystemTimeAsFileTime` instead of `gettimeofday`.
* If available at compile time, all POSIX builds now use `clock_gettime` to get the system time. If not, they fall back to `gettimeofday` or `time`.
* If available at compile time, all SDL builds now use `SDL_GetTicks64` to get the ticks since initialization count. If not, they fall back to `SDL_GetTicks`.
* …

Sample the system time at most once per Robotic command.

---

docs/changelog.txt
src/counter.c
src/run_robot.c
src/str.c
src/str.h

* Replaced tolower() usage in find_function_counter() with the faster memtolower() from memcasecmp.h.
* Optimized is_string() check for '.' by including it into the strcspn call. The new smaller is_string() is now inlineable.
* Revised the run_robot() hang detection improvement from 9ca3c82. It now masks lines_run by 0xffff, which is somehow faster!
* Partially reverted the debugger changes from 9ca3c82 since they didn't help that much or possibly made things slower.

Performance tweaks for Robotic execution.

---

.gitignore
Makefile
arch/compat.inc
arch/mingw/Makefile.in
config.sh
src/Makefile.in
src/editor/Makefile.in
src/utils/Makefile.in
unit/Makefile.in

libmingwex and several prebuilt dependencies as packaged by Fedora requires libssp. MinGW doesn't automatically link statically it (:
Also adds -fstack-protector-strong support, enables the stack protector for MinGW, and fixes some missing pthread flags.

Fix building with MinGW on Fedora.

---

contrib/rad/README.md
contrib/rad/opal.cpp
contrib/rad/player20.cpp
docs/changelog.txt

This patch ports fixes for Opal support for KSL (and a couple other things), which in turn fixes KSL in RAD v1 modules. RAD v2 modules are loaded with the KSL bits swapped to emulate Opal's broken KSL, so they work the same as before.
There's no correct way to handle KSL for RAD v2—DOS builds don't use Opal, so they produce modules with the KSL bits in the correct order. The official RAD v2s seem to have been made in the Windows or Mac ports because they rely on the wrong order.

Patch Opal envelope, KSL bugs; add player compatibility for broken RAD v2 KSL.

---

src/audio/audio.c
src/audio/audio_mikmod.c
src/audio/audio_modplug.cpp
src/audio/audio_openmpt.c
src/audio/audio_reality.cpp
src/audio/audio_vorbis.c
src/audio/audio_wav.c
src/audio/audio_xmp.c
src/audio/ext.c
src/audio/ext.h

Replaces the audio file extension checks in the audio loading system with a simple test function system. The old checks were prone to the issue that any variant extension, or lack thereof, would prevent the loading of otherwise valid files. This required adding new extensions to the list for multiple loaders every time a module format is added or a variant extension is found. This was not worth it, and extension filtering has been retained for OpenMPT builds only (as there is no other way to format filter).
To keep any added overhead minimal, the base loader now opens the input file immediately and reuses the same handle until a loader succeeds and claims/closes the handle, or until all loaders fail. This required refactoring most audio stream implementations due to the deeply nested …

Replace audio extension checks with format filter functions.

---

src/io/vfs.c
src/io/vfs.h
unit/io/vfs.cpp

Adds a few things for filesystem caching to vfs.c that were missing:
* Function to make a root in the VFS (required for Windows, DJGPP, and console ports).
* Functions to add cached files and directories to the VFS.
* Functions to invalidate cached files and directories, since they can't be moved/removed like normal VFS files.
* Function to get the total size of cached files currently in the VFS.

Add VFS cache entry creation and support functions.

---

src/io/path.c
src/io/path.h
src/io/vfile.h
src/io/vfs.c
src/io/vfs.h
src/io/vio.c
src/io/vio.h
src/io/vio_no_vfs.c
src/io/vio_posix.h
src/io/vio_win32.h
src/utils/Makefile.in
unit/io/path.cpp
unit/io/vfs.cpp
unit/io/vio.cpp

Adds support for virtual files and file caching to the vio.c stdio/unistd/dirent wrapper functions. Currently there is no way to enable this in MegaZeux itself; it is only enabled in the unit tests.

Implement vio.c virtual filesystem and file caching support.

---

config.txt
docs/changelog.txt
src/configure.c
src/configure.h
src/graphics.c
src/graphics.h
src/render_sdl.c
unit/configure.cpp

* MegaZeux now leaves the screensaver enabled by default, same as 2.84X and under. SDL 2.0.2 and up disabled the screensaver by default, preventing Windows et al. from starting a screensaver or putting monitors to sleep.
* Added a new config option `disable_screensaver` which can be used to disable the screensaver, if that behavior is preferred.
Should close #367.

Enable screensaver by default and add disable_screensaver setting.

---

docs/changelog.txt
src/editor/configure.c

Making the editor menu/help display by default again for accessibility reasons. Also, enabling show thing toggles by default because it's better than the legacy behavior in pretty much every way.

Revert editor hide help default settings, enable show thing toggles.

---

docs/changelog.txt
src/core.c
src/core.h
src/counter.c
src/counter.h
src/counter_struct.h
src/editor/debug.c
src/editor/edit.c
src/editor/robo_debug.c
src/editor/robo_debug.h
src/str.c
src/str.h
src/world.c

+ Improved the general performance of watchpoints (each watchpoint was calling snprintf once regardless of whether or not it matched).
+ Improved the performance of non-built-in counter and non-splice string watchpoints by caching counter and string pointers.
- String values are no longer allocated as part of the string struct. This was required to stabilize string pointers through the lifetime of the strings list.

Add Robotic debugger watchpoint improvements.

---

src/about.c
src/audio/audio_openmpt.c
src/io/fsafeopen.c
src/io/vio.c

* Fix clang `total` unused warning in about.c.
* Fix clang `len` used uninitialized false positive warning in
vio.c when compiled without VFS support.
* Fix MinGW `NO_EXTRA_CASE_CHECKS` unused macro warning in fsafeopen.c.
* Fix -Wsign-compare in audio_openmpt.c.

Fix misc. clang and MinGW warnings.

---

config.txt
docs/changelog.txt
src/configure.c
src/io/vio.c
src/util.c

* The check_alloc functions now attempt to free cached files before displaying an out-of-memory error. This relies on operating systems or SDKs properly returning `NULL` from `malloc` et al.
* Added missing changelog entry and config.txt documentation for the VFS.

Free VFS cached files on check_alloc out-of-memory.

---

arch/android/README.md
arch/android/project/app/build.gradle

For whatever reason, in my setup this is required so that Gradle doesn't choose to install whichever NDK versions it feels like during `make apk`.

Explicitly define Android ndkVersion in app/build.gradle.

---

docs/changelog.txt
src/configure.c

New PR since I can't rebase an archived branch. Closes #222.
Original description:
> Enables save slots on NDS, GP2X, PSP, Wii, 3DS, and Switch. It defaults to false on everything else, including Android and Emscripten.
Changes:
* Also enabled it for Dreamcast, PS Vita, and Wii U.
* Macro name tweak (attempt at consistency...).

Enable save slots by default on consoles.

---

src/window.c

This eliminates one of the several ever-growing port `#ifdef`s. POSIX does not require that `readdir` includes `..` in the list of directory contents, so it's best to handle separately and to filter out `..` if `readdir` does return it.

Use window.c console parent directory hack for all platforms.

---

docs/changelog.txt
docs/fileform.html
docs/joystick.html
docs/keycodes.html
docs/platform_matrix.html

This improves the display of fileform.html, joystick.html, keycodes.html, and platform_matrix.html for mobile and other small displays. All four documents now have an HTML viewport tag, and I've made various CSS and content tweaks to each document to improve scalability of the text content and some (but not all) tables/figures.

Mobile display improvements for most HTML documentation.

---

Makefile
arch/3ds/Makefile.in
arch/amiga/Makefile.in
arch/android/Makefile.in
arch/compat.inc
arch/darwin/Makefile.in
arch/djgpp/Makefile.in
arch/dreamcast/Makefile.in
arch/emscripten/Makefile.in
arch/gp2x/Makefile.in
arch/mingw/Makefile.in
arch/nds-blocksds/Makefile.in
arch/nds/Makefile.in
arch/nds/extmem.c
arch/pandora/Makefile.in
arch/psp/Makefile.in
arch/psvita/Makefile.in
arch/switch/Makefile.in
arch/wii/Makefile.in
arch/wiiu/Makefile.in
config.sh
contrib/icons/Makefile.in
docs/changelog.txt
src/configure.h
src/io/vio.h

Adds `--host` to config.sh and its corresponding variable `CROSS_COMPILE` to the build system (previously only used by the Pandora port). This is mainly for Linux, but it also simplified the toolchain variables for several architectures. This required changing how the console ports override `STRIP` and moving `--strip-unneeded` from that variable.
Additionally, I fixed these warnings:
* 3DS, NDS: `as` would repeatedly complain about missing end-of-file newlines caused by `bin2s`.
* NDS: fixed `#ifdef` used inside of the macro `info()`.
* PSP: C++98 whining about `long long` and commas at the end of enum declarations.

Add --host config.sh option and CROSS_COMPILE Makefile variable.

---

docs/changelog.txt

2.93's changelog got to be quite a mess, so I've recategorized it and sorted it. It is the longest changelog of any MZX version (nearly 400 pre-wrapped lines), so I've subdivided it into several sections and summarized most to make it less overwhelming.

Changelog reformat, add changelog blurb for 2.93.

---

docs/changelog.txt
testworlds/run.sh

* MZX 2.93 broke getting the process ID from mzxrun in run.sh.
* Fixed a run.sh edge case that seems to occur only in chroot: mzxrun will not always appear in the process list unless `-e` is provided.

Fix testworlds PID check and ps edge case found using chroot.

---

Makefile
arch/3ds/Makefile.in
arch/emscripten/Makefile.in
arch/switch/Makefile.in
arch/wiiu/Makefile.in
config.sh
docs/changelog.txt
unit/Makefile.in

* Added --enable-lto for enabling link-time optimization.
* The default debug optimization level is now -Og.
* Sanitizer flags are now applied independently of release/debug.
* Removed redundant optimization flags from console ports.

Improve the handling of optimization flags, add --enable-lto.

---

docs/changelog.txt
src/io/vio_posix.h

Found via the mzvplay.txt conversion of the Mackey Mounse cartoon, which uses `FREADn` several times per frame. For some reason, each `FREADn` would take ~30ms per call (per Lancer-X), which I found is caused by the `fstat` used in POSIX `platform_filelength`. Due to the way frame delays are handled by mzvplay.txt, it would immediately try to load the next frame, causing hangs.

Fix poor HTML5 vfilelength performance.

---

arch/switch/pad.config
config.txt
docs/changelog.txt
docs/joystick.html
src/configure.c
src/configure.h
src/event.h
src/event_sdl.c
src/platform_sdl.c
unit/configure.cpp

* Most references to "gamecontrollers" in code and config settings are now "gamepad", which is half the length, less annoying to type and look at, and also matches SDL3's current renaming of their API. The old "gamecontroller" config settings still work, but config.txt now only contains references to "gamepad".
* The SDL event unicode fallback behavior now only triggers when text events are disabled in SDL2+. This should allow text input events if the onscreen keyboard is active in the Android port, but still allow the unicode fallback to work when it's hidden. Text input is now disabled whenever a platform supports an onscreen keyboard instead of being excluded by Android specifically.
* SDL joystick GUIDs are now derived from the `SDL_Joystick *` rather than the SDL device index. The …

SDL3 preparation (event_sdl.c).

---

docs/changelog.txt
src/render_glsl.c

Using the Intel HD Graphics 2500 driver for Windows 10 and possibly some other old graphics drivers (the [SDL documentation cites macOS](https://wiki.libsdl.org/SDL2/SDL_GL_SwapWindow)), swapping to a framebuffer other than 0 prior to calling SDL_GL_SwapWindow can cause the screen to flicker or not display at all. This was occurring in the GLSL renderer, though for some reason only with `glslscale` (and not `glsl`).

Fix glslscale bug when binding a framebuffer before gl_swap_buffers.

---

.github/workflows/main.yml
arch/nds-blocksds/Makefile.in

Builds the same code, just in a somewhat more future-proof and cleaner manner.
Also added a regression test, as the BlocksDS target is faster-moving.

nds-blocksds: Clean up/update Makefile, add GitHub CI support.

---

docs/changelog.txt
src/editor/robo_ed.c

Fix robot editor hangs when using Replace All on quotes/extras.

---

docs/changelog.txt
src/game_update.c
src/graphics.c
src/graphics.h

* The board message now clips at the correct position when it overflows the right edge of the board. Previously, it would always be clipped at BYTE 80 instead of after the final byte that would display on screen. This caused wrapping bugs with non-centered message columns >0 and would clip messages containing color codes too early.
* When the board message clips the right side of the screen, the next line displayed will now use the correct color code from the previous line (as if no clipping had occurred) instead of whatever the last color that displayed on the screen was.
* Fixed some minor errors in `color_string_length` and `color_string_index_of`. They should now behave identically to the old `strlencolor` with regards to color codes and escapes. They also now take `const` string …

Fix board message clipping and color code behavior.

---

docs/changelog.txt
src/graphics.h
src/intake.c
src/intake.h
src/scrdisp.c
src/window.c

Games made for MegaZeux versions between 2.80h and 2.91f (inclusive) can rely on scrolls displaying their text using the protected palette. Adding support for this (locked to versions between 2.80X and 2.90X) fixes a scroll in Welkin.
Also added a toggle to the scroll editor to view a scroll using the game colors and charset and unbroke the protected palette frame display (broken a few commits ago while fixing color code display).

Fix scroll colors for games that rely on protected palette scrolls.

---

arch/3ds/audio.c
arch/djgpp/audio.c
arch/dreamcast/audio.c
arch/wii/audio.c
docs/changelog.txt
src/audio/audio.c
src/audio/audio.h
src/audio/audio_sdl.c
src/audio/audio_struct.h
src/audio/audio_wav.c
src/audio/audio_xmp.c
src/audio/sampled_stream.cpp
src/configure.c
src/configure.h
unit/configure.cpp

* Software mixer configuration is now performed by audio_mixer_init, which does basic sample rate checking and bounding on the buffer size and number of channels.
* The software mixer render function now takes a number of frames, channels, and the sample format instead of a number of bytes. It is up to the audio driver to calculate the number of frames needed if its API requests a number of bytes instead. The supported sample formats are SAMPLE_S16, SAMPLE_S8, and SAMPLE_U8.
* The software mixer now ignores audio streams with a NULL mix_data function instead of crashing. Nothing currently relies on this.
* The SDL audio driver will select whichever sample rate is returned by SDL_OpenAudioStream now instead of using the input value.

Move software mixer configuration out of audio driver code.

---

arch/djgpp/platform.c
docs/changelog.txt

Fixes [issue 857](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=857).

Fix the TIME and DATE counters in DOS when TZ is unset.

---

docs/changelog.txt
src/audio/audio_mikmod.c
src/audio/audio_modplug.cpp
src/audio/audio_openmpt.c
src/audio/audio_reality.cpp
src/audio/audio_vorbis.c
src/audio/audio_wav.c
src/audio/audio_xmp.c
src/audio/sampled_stream.cpp
src/audio/sampled_stream.h

Removes the old negative compensation code and replaces it with a much more straightforward way of handling resampling. This should fix the following bugs:
* sampled_mix_data no longer discards audio data if the requested number of frames is smaller than what the buffer is configured for. This was causing audio skips in the SDL3 port.
* sampled_mix_data no longer discards audio data when the input buffer is resized e.g. by changing the playback frequency. This fixes audible pops in games that set `MOD_FREQUENCY` a lot.
* Not a bug, but the old way of having each player calculate the current buffer position and remaining space in the buffer looked fragile. This is done in a sampled_stream function now out of necessity, so this should be less prone to breaking.

Rewrite software mixer resampler prologue and epilogue handling.

---

arch/djgpp/audio.c
arch/djgpp/driver_sb.h
arch/djgpp/platform.c
arch/djgpp/platform_djgpp.h
docs/changelog.txt

Add support for Sound Blaster Pro and Sound Blaster 16 8-bit modes.

---

docs/changelog.txt
src/utils/ccv.c
src/utils/image_file.c
src/utils/image_file.h
src/utils/png2smzx.c
unit/utils/image_file.cpp

ccv and png2smzx now return slightly more useful error messages when an image fails to load.

Add load_image_from_[...] error codes and image_error_string.

---

src/render_layer.cpp
src/render_layer_code.hpp

Removing the static `PPAL` variable from the software layer renderers reduces the total number of renderers by 1/3 and opens up the possibility of 8-bit ppal=240 rendering in the future without needing extra renderers. This seems to overall have no impact whatsoever on performance, with maybe a very slight performance benefit on average (still testing).
64-bit: 108 → 72
32-bit: 72 → 48
HTML5, Wii, Vita: 12 → 8
Android: 24/12 → 16/8

Remove PPAL from the software layer renderers.

---

docs/changelog.txt
src/render_layer_code.hpp

* Minor changes/improvements for MZX 1PPW, SMZX 1PPW, SMZX 2PPW transparent rendering.
* SMZX 4PPW+ renderers now use `set_colors_smzx` to generate color lookup tables.
* MZX 2PPW+ and SMZX 4PPW+ transparent renderers now use opacity masks generated with `set_colors_*`, resulting in large performance improvements in many cases and simplifying the renderer code.

Use opacity masks when software rendering transparent layers.

---

Makefile
arch/djgpp/CONFIG.DJGPP
arch/djgpp/Makefile.in
config.sh
docs/changelog.txt
docs/platform_matrix.html
src/about.c
src/audio/audio.c
src/audio/audio_struct.h
src/audio/audio_vorbis.c

* Added stb_vorbis support. DOS builds are now forced to build with stb_vorbis. This fixes crashes during Ogg Vorbis playback due to `malloc`/`free`/stdio usage in libvorbis/libtremor corrupting the heap during the audio interrupt.
* DOS builds now defer mix function audio stream destruction to a garbage list that is collected when the main thread creates or destroys audio streams. This fixes crashes during general audio playback due to `free`/other destructor function usage corrupting the heap during the audio interrupt.

Add stb_vorbis support for DOS builds, fix DOS audio crashes.

---

src/render_gp2x.c
src/render_sdl.c
src/render_sdl.h
src/render_sdlaccel.c
src/render_soft.c
src/render_softscale.c
src/render_yuv.c

SDL3 uses const equivalents to `SDL_PixelFormat` that have to be acquired in a different way from SDL1.2 and SDL2. This combines the remaining SDL-based update_colors renderer functions and adds an intermediary const `SDL_PixelFormat` to hopefully make the switch slightly easier.

Merge all SDL renderer update_colors functions.

---

arch/darwin/Makefile.in
arch/darwin/MegaZeux.plist
arch/darwin/bundle.sh
arch/darwin/dmg.sh
docs/changelog.txt
scripts/deps/Makefile

Also adds a changelog entry for the darwin-dist overhaul and updates SDL2 latest to 2.30.6.

Fix darwin-dist Gatekeeper errors caused by bad codesign handling.

---

config.sh
docs/changelog.txt
src/io/fsafeopen.c
src/io/path.c
src/io/path.h
src/io/vfs.c
src/io/vio.c
unit/io/path.cpp
unit/io/vfs.cpp

* Added support for Windows UNC paths. Host/share and \\?\unc\ format paths are not supported by the VFS and will never be cached.
* Linux and macOS now allow colons in path names. VFS roots for these platforms require a double slash after the colon to be recognized.
* fsafetest now rejects colons ANYWHERE in a path string instead of as the second character. This fixes potential usage of fat:/ et al.

Support UNC paths, Linux/macOS colon paths, reject colons in fsafetest.

---

arch/darwin/Makefile.in
docs/changelog.txt
scripts/deps/Makefile
scripts/deps/Makefile.macos.in
src/platform_endian.h

Misc. cleanup and fix patches for scripts/deps.

---

arch/3ds/CONFIG.3DS
arch/android/CONFIG.ANDROID
arch/djgpp/CONFIG.DJGPP
arch/dreamcast/CONFIG.DC
arch/emscripten/CONFIG.HTML5
arch/nds-blocksds/CONFIG.NDS
arch/nds/CONFIG.NDS
arch/psvita/CONFIG.PSVITA
arch/switch/CONFIG.SWITCH
arch/wii/CONFIG.WII
arch/wiiu/CONFIG.WIIU
debian/rules
docs/changelog.txt
megazeux.spec
scripts/buildscripts/mzx-scripts/platforms/windows-x64.sh
scripts/buildscripts/mzx-scripts/platforms/windows-x86.sh

Also updates megazeux.spec for MZX 2.93b.

Enable link-time optimizations by default for most platforms.

---

docs/changelog.txt
src/editor/edit.c

Broken by #455, which missed one spot that still relied on the old hacky usage of `overlay_mode` in the editor display routine.
Fixes [issue 867](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=867).

Fix show thing regression caused by overlay_mode fixes.

---

docs/changelog.txt
src/editor/sfx_edit.c
src/intake.c

Commit 25d638bd repurposed the original `cur_char`, which originally held the input internal keycode. It was changed to instead do nothing in 0d725815 when SDL_TEXTINPUT handling was implemented, however, the original exit check prior to text input wasn't removed. Repurposing this variable reactivated that check and caused some text input fields to stop accepting input altogether (dependent on data stored in old board names, or particularly in the SFX editor, uninitialized memory).
Since the check has been dead for a while with fundamentally no problems, it has been removed entirely. The variable has been renamed to avoid being shadowed by the new handler, which also uses `cur_char`. Finally, the SFX string buffers in the SFX editor are cleared now (to avoid potential MSan whining if the …

Fix bug where intake would sometimes skip handling input text.

---

arch/3ds/render.cpp
arch/djgpp/render_ega.c
arch/djgpp/render_svga.c
arch/dreamcast/render.c
arch/dreamcast/render_fb.c
arch/nds/render.c
arch/wii/render_gx.c
arch/wii/render_xfb.c
src/configure.h
src/graphics.c
src/graphics.h
src/render.c
src/render.h
src/render_gl.c
src/render_gl.h
src/render_gl1.c
src/render_gl2.c
src/render_glsl.c
src/render_gp2x.c
src/render_sdl.c
src/render_sdlaccel.c
src/render_soft.c
src/render_softscale.c
src/render_yuv.c
unit/render.cpp

This fixes numerous comments complaining about `fix_viewport_ratio` being used in render functions by instead calculating the viewport whenever the window is resized with a new, similar function in graphics.c. Doing this also allows the integer scaling state to be precalculated for all scaling renderers, which helps mainly `opengl2` right now (but could be extended to `opengl1` and `glsl`). The longstanding "FIXME" about the ratio being calculated using floats has also been resolved.
There are two places where this couldn't be fully fixed: `opengl2` and `glsl` using the viewport variables in `render_layer` to set the viewport every time a layer is rendered. Doing this correctly requires a new start of frame callback, which would be a good idea for other reasons (charset and palette …

Merge/cleanup renderer viewport calculation code.

---

docs/changelog.txt
src/graphics.c
src/render_sdl.c

* `graphics.resolution_width/height` are unsigned, so the auto value should be 0.
This only kind of worked before by mistake and it was getting past the filter
in the `software` renderer's `init_video` function.
* `fullscreen_windowed` is now handled entirely by the renderer.
* Bumped the minimum automatic fullscreen size back up to 640x350. The `gp2x`
renderer overrides it anyway and 320x240 is quite bad for `software`.
* The `software` and `gp2x` renderers now enable blitting when the window
surface is too small instead of crashing. SDL3 in Wayland reports several sizes
smaller than 640x480, which made it possible to encounter this bug finally.

Misc. fullscreen tweaks/fixes.

---

src/network/Socket.cpp
src/platform.h
src/platform_sdl.c
src/platform_time.c
src/render_egl.c
src/render_egl.h
src/render_gl.c
src/render_sdl.h
src/util.h

SDL3 uses SDL_FunctionPointer instead of void * for function pointers, which introduces function/object aliasing warnings. Instead of using SDL_FUNCTION_POINTER_IS_VOID_POINTER to work around this (which introduces more warnings in unrelated places), it's easier to just combine all of the places these functions are used into platform_* functions. GL_GetProcAddress still requires a separate hack.

Move SDL_LoadObject et al. to platform_sdl.c to fix warnings.

---

.github/workflows/main.yml
arch/zip.inc

Removes the only extra dependency for platforms that rely on Debian-based containers for CI, which should hopefully resolve the recent failures.

p7zip is no longer a hard dependency for make archive.

---

arch/android/Makefile.deps
arch/android/Makefile.in
arch/android/SDL2-page-sizes.patch
arch/android/libogg-Android.mk
arch/android/libvorbis-Android.mk

As of Android 15, devices will be able to ship with 16 KB page sizes instead of the previous default of 4 KB. This requires updating the NDK (which we are not doing as to keep compatibility with API level 16 for 2.93c) or adjusting the build process of all shared libraries (which is done by this commit).

android: Support 16K page sizes.

---

docs/changelog.txt
src/platform_endian.h
src/render_layer.cpp
src/render_layer_code.hpp
src/render_layer_common.hpp
unit/render.cpp

* Port same subpalette optimization for 4PPW and 8PPW renderers from render_layer32x4.
* Port precalculated clip boundaries optimization from render_layer32x4.
* Implement unaligned rendering optimization comparable to most vector renderers.
Improves all layer renderers for x86-64, AArch64 (if supported), POWER8, and Emscripten;
improves 8-bit and 16-bit layer renderers for x86, PowerPC, and M68k.

Software layer renderer clipping and unaligned enhancements.

---

arch/manifest.sh
docs/changelog.txt
scripts/buildscripts/mzx-scripts/crlf.sh

* Removed Bash-style function declaration. (Bash extension)
* Removed function export. (Bash extension)
* Explicitly provide . to find. (ShellCheck)
* Use ! instead of -not for find. (some BusyBox builds apparently)
* Rewrite xargs invocation to use -n1 instead of -I{}. (xargs warning)
* The manifest entry script is now provided directly to xargs instead of in a function, which looks worse, but is POSIX-compatible.
* Replace legacy backtick usage with $(). (ShellCheck)
* Double quote all variable expansions. (ShellCheck)
* Double quote space separator argument to cut. (ShellCheck)
* Use set -e for cd. (ShellCheck)
* Use sort -k3 instead of --key=3. (BusyBox)

Remove bashisms and other issues from manifest.sh.

---

Makefile
arch/unix/Makefile.in
contrib/libxmp/Makefile.megazeux
docs/changelog.txt
src/Makefile.in
src/about.c
src/editor/clipboard_cocoa.m
src/event_sdl.c
src/io/vfs.c
src/io/zip.c
src/legacy_board.c
src/legacy_world.c
src/platform_time.c
src/pngops.c
src/render_gl.h
src/robot.c
src/thread_dummy.h
src/utils/ccv.c
src/utils/checkres.c
src/utils/image_file.c
src/utils/txt2hlp.c
unit/intake.cpp

* Fix various ctypes.h char array subscript warnings in the utilities (NetBSD).
* "Fix" several OpenBSD ld nags about safe uses of `strcpy`.
* Fix unused `utf8_next_char` warning for SDL 1.2 builds.
* Suppress SDL 1.2 glext.h `GL_GLEXT_VERSION` redefinition warnings caused
by outdated defines in SDL_opengl.h by replacing `sdl-config` `-I` with `-isystem`.
* Fix GCC 4.6.2 and older bogus eocd uninitialized warnings.
* Fix errors from old libpng versions predating `png_set_add_alpha`.
* Fix warnings/errors from old libpng versions predating `png_const_bytep`.
* Fix compilation failures from old glibc versions where `clock_gettime` is in `-lrt`.
* Remove `-Wno-missing-field-initializers` from libxmp to fix GCC 3.4 compilation.
* Remove redundant order-only prerequisite usage in …

Fix misc. BSD and SDL 1.2 warnings.

---

config.sh
docs/changelog.txt
src/io/vfs.c
src/io/vfs.h
src/io/vio.c
testworlds/run.sh
unit/Makefile.in
unit/io/vfs.cpp

Fix OS detection, unit tests, and testworlds for Haiku.

---

.gitignore
arch/3ds/Makefile.in
arch/dreamcast/Makefile.in
arch/emscripten/Makefile.in
arch/mingw/Makefile.in
arch/nds-blocksds/Makefile.in
arch/nds/Makefile.in
arch/psp/Makefile.in
arch/psvita/Makefile.in
arch/switch/Makefile.in
arch/unix/Makefile.in
arch/wii/Makefile.in
arch/wiiu/Makefile.in

Revert the creeping introduction of Bash-only globs to several architecture `clean` rules. This should fix `make clean` for MinGW and console platforms in Linux/BSD/etc. environments where `/bin/sh` is not Bash (Alpine, Debian, every BSD). Also fixes several instances of misusing or not using `${RM}`.

Remove make clean Bashisms from most arch Makefile fragments.

---

arch/psp/Makefile.in
arch/psp/platform.c
src/io/vio.c
src/io/vio_posix.h
src/util.c

* Remove quotes from MZX version in application title.
* Work around broken PSPSDK readdir never returning NULL; the PSP port treats "" as a sentinel for now.
* Work around EBOOT.PBP being treated as a directory in find_executable_dir.
* Disable PSP_MODULE_INFO for SDL2+, link libSDL2main.
* Support SDL3 on PSP.
The PSP port post-devkitPSP is still unusably broken due to numerous filesystem issues, including:
* Files are length zero most of the time. This prevents CAVERNS.MZX from loading in any build, and prevents the charsets and config.txt from being loaded in SDL2 and SDL3 builds (but not SDL 1.2???).
* Directories are always length zero, breaking the file manager.
* stat unconditionally returns a success; non-existent files are treated identically to directories.

Add workarounds for misc. PSPSDK issues.

---

docs/changelog.txt
src/game.c

* MegaZeux 1.x worlds no longer send key labels except A-Z.
* MegaZeux 2.00 to 2.61 worlds no longer send key labels except A-Z 1-9.

Add version checks to KEY? and KEYENTER labels.

---

docs/changelog.txt
src/editor/edit.c
src/editor/world.c

The editor would mark the blank world created on initialization as active, but not any blank worlds created afterward during editing. This would cause blank worlds created by Alt+R and failed __TEST.MZX reloads to be "inactive", which as of 2.91g, has special handling in the game.c draw function to skip drawing the screen and instead constantly display the intro timer.
The fix is to just set this flag in create_blank_world where it should have been doing it anyway.
While the most noticeable issue this caused started in 2.91g, the underlying bug has existed since 2.80, and affected various other minor things that used `mzx_world->active` as well.

Mark all new worlds created in the editor as active.

---

arch/unix/README
docs/platform_matrix.html

+ Fixed clang versions for Xcode (using 14.2, not 12.2).
+ Now using BlocksDS 1.9.1 to buid the Nintendo DS port.
+ Now using Linux devkitPSP r17 to build the PSP port.
+ Split executable format off of architecture field.
+ Split libc off of toolchain field.
+ Split SDL field into separate fields for SDL 1.2, SDL2, and SDL3. "N/A" in this case means it's not provided by the upstream packager yet or is irrelevant to the platform; "TBA" indicates lack of triage, or intentional delay due to forced system requirements increase; "faulty" indicates a serious issue blocking the switch. In the case of MinGW/MSVC, the new default SDL_renderer driver direct3d11 has terrible performance. In the case of PSPDEV, SDL2 and SDL3 are semi-supported by the buildsystem and are packaged, but PSPDEV's Newlib …

Misc. updates to platform_matrix.html.

---

arch/3ds/event.c
arch/3ds/keyboard.c
arch/3ds/pad.config
arch/android/README.md
arch/djgpp/event.c
arch/dreamcast/event.c
arch/nds/event.c
arch/nds/pad.config
arch/nds/render.c
arch/nds/render.h
arch/wii/event.c
config.txt
docs/changelog.txt
docs/joystick.html
src/SDLmzx.h
src/event.c
src/event.h
src/event_sdl.c
src/platform_dummy.c
unit/configure.cpp

+ Added common screen keyboard functions and a port-independent configuration option "joy#.show_screen_keyboard" to select a joystick action to display the screen keyboard. If the platform's screen keyboard supported function indicates that a screen keyboard is currently supported, MegaZeux will hijack this joystick button for toggling the screen keyboard instead.
+ Added support for SDL screen keyboards. Currently, SDL supports system screen keyboard triggers for Android and Vita, plus some cases in Windows and Linux (only really care about Steam Deck and stuff like postmarketOS out of these).
+ NDS and 3DS ports now use common screen keyboard support functions for toggling instead of their own custom triggers.
+ Added Android 3-point touch screen keyboard trigger (hack).
+ Misc. trace …

Initial SDL screen keyboard support and common functions.

---

arch/3ds/event.c
arch/djgpp/event.c
arch/dreamcast/event.c
arch/nds/event.c
arch/wii/event.c
src/event.c
src/event.h
src/event_sdl.c
src/platform_dummy.c

Fixes screen keyboard triggers failing the first time they're used after the screen keyboard is closed via the OS user interface e.g. Android's back button.

Use SDL_ScreenKeyboardShown instead of internal state.

---

config.txt
docs/changelog.txt
src/event.c

SDL's SteamOS screen keyboard trigger currently seems nonfunctional for org.freedesktop.Platform 24.08/SDL2 2.32.4 (possibly related: https://github.com/libsdl-org/SDL/issues/12595) and SteamOS already has a shortcut for this, meaning MegaZeux doesn't need to sacrifice a gamepad button to open the screen keyboard in Linux.

Disable the screen keyboard gamepad action by default on Linux.

---

.github/workflows/main.yml
arch/install.inc
arch/unix/megazeux.metainfo.xml
config.sh
docs/changelog.txt
megazeux.spec
scripts/pkg/README.md
scripts/pkg/flatpak/com.digitalmzx.MegaZeux.yml
src/editor/ansi.c

- `update_contact`?
- Icon doesn't meet spec, can replace at a later date.

Add AppStream metainfo.xml file and config.sh --metainfodir.

---

src/editor/ansi.c
src/nostdc++.cpp

+ Fix ansi.c warning caused by macOS defining snprintf as a macro.
+ Fix nostdc++.cpp GCC 15 warning caused by noexcept.

Misc. warnings fixes.

---

src/event.c
src/event.h
src/event_sdl.c

* Suppress the automatic IKEY_RETURN presses the Vita screen keyboard sends for no good reason after text input.
* Expand the maximum size of the unicode text buffer to 1024.

PlayStation Vita keyboard bugfixes.

---

docs/changelog.txt
src/render_gl1.c
src/render_gl2.c
src/render_glsl.c

* Explicitly set OpenGL clear color in all OpenGL renderers and explicitly clear the entire frame with it every resize to fix transparent letterbox areas in Wayland and possibly other places.
* Fix opengl1 renderer not setting a transparent color in the flat palette, causing some (but not all) colors to be transparent in Wayland.
* Change initial screen texture fill in opengl2, glsl renderers to transparent instead of white to fix white edge line bugs in most environments.

Fix OpenGL renderer alpha bugs affecting Wayland, white edge lines.

---

arch/android/project/app/src/main/java/net/digitalmzx/megazeux/MainActivity.java
docs/changelog.txt

Android: don't overwrite assets with newer modified times.

---

src/graphics.c
src/render_sdl.c
src/util.c
src/util.h

Fixes unix-devel issues where a missing icon warning would be printed when changing the renderer after changing out of `SHAREDIR`.

Add ICONFILE to MZX resource system.

---

scripts/deps/Makefile
src/expr.c
src/intake.c
src/render_sdl.c
unit/Makefile.in

* Disable Vorbis ogg linking test for scripts/deps. Fixes libvorbis compilation issues for `PLATFORM=linux-msan` found in an Ubuntu chroot.
* Regression tests were missing `ZLIB_CFLAGS` (found in Ubuntu chroot MSan builds).
* SDL icon surfaces could be leaked when failing to set the surface (occurs with the SDL dummy renderer).
* Fixed case where intake Ctrl+Left could cause out-of-bounds reads.
* Added guards for `get_string` calls in expr.c.
* Copyright for original `tr_msg` in expr.c.

Misc. minor fixes.
