AliceLR/megazeux

src/graphics.c, src/mzm.c, src/render_gl2.c, src/render_glsl.c, src/render_layer_code.h
I felt that these were the files I most significantly modified.
Also removed some junk leftover comments from layer_render_code.h
=> Added new copyright notices to some source files

assets/shaders/extra/emboss.frag, assets/shaders/extra/epx.frag
Ensure that both are working fine without warnings before pulling.
=> Fixes for EPX and emboss shaders

src/context_enum.h, src/editor/block.c, src/editor/char_ed.c, src/editor/debug.c, src/editor/edit_di.c, src/editor/pal_ed.c, src/editor/param.c, src/editor/robo_debug.c, src/editor/sfx_edit.c, src/editor/window.c, src/game.c, src/updater.c, src/window.c, src/window.h
Added new help contexts for the updater, counter debugger, robot
debugger and breakpoint editor. Contexts have been enumerated in
context_enum.h. Multiple instances of extra context pushes/pops have
also been fixed.
=> Help context changes

assets/shaders/extra/crt.frag
A dumb shader that looks a little CRTish
=> A silly CRT shader

debian/changelog, debian/control, debian/copyright
Debian rules files updated for 2.90.
=> Fixed debian rules

arch/darwin/Makefile.in, src/Makefile.in
Made necessary changes to Makefiles, as suggested by Spectere, to allow compilation under macOS, with SDL2's requirements.
=> Altered Makefiles for macOS compilation

assets/shaders/tilemap.smzx.frag
=> Fixed GLSL for Intel HD (seriously)

arch/unix/Makefile.in, debian/changelog, debian/docs
Also updated Debian changelog.
=> Fixed debian and linux build systems to reflect removed files. 

assets/shaders/scalers/crt-wave.frag, assets/shaders/scalers/crt.frag
=> Improvements to crt.frag, addition of crt-wave.frag

debian/changelog
=> Fixed dates in debian changelog.

src/sprite.c
=> Fixed unbound sprite clipping bug

arch/wii/thread.h, src/network/dns.c, src/network/manifest.c, src/platform.h, src/thread_pthread.h, src/thread_sdl.h
Added thread cond functions to MegaZeux to facilitate improvement in networking code and the D3D11 renderer.
=> Added thread cond functions to SDL/pthread/Wii implementations.

Makefile, arch/3ds/Makefile.in, arch/3ds/render.c
I leave the buildscripts to you.
=> fix for devkitARM r49, use official portlibs

src/str.c
Fixes this bug: http://www.digitalmzx.net/forums/index.php?app=tracker&showissue=714
Unit tests here: https://gist.github.com/iamgreaser/427d20b42f40bc478603f3bde8733b0b
Amusingly valgrind says "no leaks are possible" despite there being an `mmap` without an `munmap`, but that one's kinda deliberate. It can also be forced to emulate pre-bugfix behaviour rather than matching `strcmp` / `strcasecmp`.
=> Fix differing-length string comparison issues

version.inc
Updated the Xcode project to work with the modular audio system.
=> Xcode Updates

arch/3ds/event.c, arch/3ds/render.c, arch/3ds/shader_playfield.g.pica
Also removed some no-longer-necessary GPU sending.
=> fix 3ds focus not working on init

debian/changelog
Pulling this prior to asking makes my script's job easier :P
=> Debian changelog work for 2.91f. Time permitting, pull just prior to asking for debian builds, please.

debian/changelog
=> Debian changelog for 2.91g

arch/xcode/MegaZeux.xcodeproj/project.pbxproj
=> Updated Xcode project for the v2.91g build.

debian/changelog
Changelog edits for v2.92, as usual.
=> Debian changelog for v2.92

debian/changelog
=> New changelog entries for Debian.

arch/msvc/Core.vcxproj, arch/msvc/Core.vcxproj.filters, arch/msvc/Editor.vcxproj, arch/msvc/MZXRun.vcxproj, arch/msvc/MegaZeux.vcxproj, src/render_layer_code.hpp
* Updated the MSVC solution so that it builds the new C++ render_layer implementation.
* Minor code updates to allow MSC to build the project.
=> MSVC Solution Update (C++ render_layer impl)

arch/xcode/MegaZeux.xcodeproj/project.pbxproj
* Changed render_layer to the new C++ revision.
* Added dir.c/h.
* Moved more options out of the individual projects and into the main workspace.
=> Update the xcode project.

debian/changelog
Okay, let's try this with the right base branch...
=> Debian Changelog fixes for v2.92d

arch/msvc/Core.vcxproj, arch/msvc/Core.vcxproj.filters, arch/msvc/Editor.vcxproj, arch/msvc/Editor.vcxproj.filters, arch/msvc/msvc.h, src/io/memfile.h
* Included added/moved files into the project.
* Updated filters to better mimic the source directory structure.
* Added defines to allow access() calls to work properly.
* Added explicit stdio.h include to memfile.h.
=> Updated MSVC project for 2.92d.

arch/msvc/Core.vcxproj, arch/msvc/Core.vcxproj.filters
Links to the new files, adds a couple of preprocessor definitions, yadda yadda.
=> MSVC Project Update (October 2020)

src/editor/board.c, src/editor/board.h, src/editor/world.c, src/io/zip.c, src/io/zip.h, src/legacy_board.c, src/legacy_board.h, src/legacy_robot.c, src/legacy_robot.h, src/legacy_world.c, src/legacy_world.h, src/mzm.c, src/utils/downver.c, src/world.c, src/world.h, src/world_struct.h
Replaces the usage of FILE with vfile in world.c, legacy_world.c, etc. and cleans up legacy world loading a little bit (in preparation for some changes to the way world decryption works).
=> Use vfile instead of stdio for world file IO.

arch/3ds/audio.c, arch/3ds/platform.c, arch/nds/platform.c, arch/wii/audio.c, arch/wii/event.c, arch/wii/platform.c, src/platform.h, src/platform_dummy.c, src/platform_sdl.c
Gets rid of the last few usages of the SDL fixed width integer types in non-SDL places.
=> Remove remaining non-SDL usage of SDL fixed width int types.

.github/workflows/main.yml
=> Use make -j4 in workflows to better use multicore GitHub runners.

unit/Unit.hpp
This cuts the unit tests' build times by *half or more* in MINGW64.
=> Stop using iostream and sstream in the unit tests.

README.md
I would like my credit here to be more easily associated with my current online presence, as opposed to a dead handle. Feel free to request a shorter credit, though.
=> Update my credit in the README.md

src/board.c, src/io/memfile.h, src/io/vio.c, src/io/zip.c, src/mzm.c, src/old/legacy_save.c, src/robot.c, src/utils/downver.c, src/world.c, src/world_format.h, unit/io/memfile.cpp, unit/world.cpp
sdfsdgsdfhfghfgfdgvvbcbvcbvcbvc
=> Fix GCC 11 -Wmaybe-uninitialized warnings for mfopen.

arch/android/Makefile.deps, arch/android/config_types.h, arch/android/project/app/build.gradle, arch/android/project/app/src/main/AndroidManifest.xml, arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java, arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java, arch/android/project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java, arch/android/project/app/src/main/java/org/libsdl/app/SDL.java, arch/android/project/app/src/main/java/org/libsdl/app/SDLActivity.java, arch/android/project/app/src/main/java/org/libsdl/app/SDLAudioManager.java, arch/android/project/app/src/main/java/org/libsdl/app/SDLControllerManager.java, arch/android/project/build.gradle, arch/android/project/gradle/wrapper/gradle-wrapper.properties
* SDL2: 2.0.12 -> ~~2.0.16~~ 2.0.18
* libogg: 1.3.3 -> 1.3.5
* libvorbis: 1.3.6 -> 1.3.7
=> Update Android dependencies and build script.

config.sh
Yeah this kind of broke DJGPP and probably Dreamcast. OOpsie woopsie!!!1
=> Force disable dummy software renderer for all custom code platforms.

docs/fileform.html, docs/joystick.html
=> More fixes/tweaks for fileform.html and joystick.html.

docs/WIPHelp.txt
**All work in this commit is Terryn's, not my own.**
=> Update WIPHelp.txt for MegaZeux 2.93.

arch/djgpp/render_svga.c
Improved the comments a bit, fixed error checks to actually check for errors (not just function support).
The other change is that the SVGA renderer now uses `BL=80h` to queue setting the palette and display page at VSync, rather than spinning the CPU until that happens. This should lead to better performance, at the cost of a very minor edge case when the palette upload happens before VSync, but the display page change happens after VSync (=> so on the next frame). 
It is probably a good idea to test this on real hardware.
=> djgpp: Clean up render_svga.c, use vertical retrace palette/display flip

docs/changelog.txt, src/game_update.c, src/graphics.c, src/graphics.h, src/intake.c, src/intake.h, src/robot.c, src/scrdisp.c, src/scrdisp.h, src/window.c
This is really more like implementing a feature I was going to but forgot to add with initial 1.x support...
=> Fix color scroll editing, increase max scroll line length to 255.

src/editor/robo_ed.c, src/expr.c, src/legacy_robot.c, src/rasm.c, src/robot.c
Fixes [240](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=240).
=> Robotic 3: add counter and expression support to bracket interpolation.

.github/workflows/main.yml, docs/changelog.txt, src/editor/block.c, src/extmem.c
Fixes [issue 870](https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=870).
=> Load the source board from extra memory during editor copy block.

arch/emscripten/web/package.json, arch/emscripten/web/rollup.config.js
=> Update node dependencies for Emscripten port.
